#!/usr/bin/env node
const slugify = require('slugify')
const ejs = require('ejs')
const fs = require('fs')
const path = require('path')
const glob = require('glob')
const yaml = require('js-yaml')

const exerciseFiles = glob.sync('exercises/*.yml')
const exercises = new Set()
const arrays = ['progressions', 'videos', 'regressions', 'muscles', 'tags']
let lastUpdated
for (const file of exerciseFiles) {
  const exercise = yaml.load(fs.readFileSync(file, 'utf8'))
  const updated = exercise.updated = fs.statSync(file).mtime
  if (lastUpdated === undefined) lastUpdated = updated
  else if (updated > lastUpdated) lastUpdated = updated
  exercise.slug = slugify(exercise.name)
  for (const arrayKey of arrays) {
    if (!Array.isArray(exercise[arrayKey])) exercise[arrayKey] = []
  }
  exercises.add(exercise)
}

const tags = new Map()
const muscles = new Map()
for (const exercise of exercises.values()) {
  for (const progressionName of exercise.progressions) {
    const progression = Array.from(exercises).find(exercise => exercise.name === progressionName)
    if (!progression) {
      throw new Error(`${exercise.name} referenced unknown progression ${progressionName}`)
    }
    progression.regressions.push(exercise.name)
  }

  for (const muscle of exercise.muscles) {
    if (!muscles.has(muscle)) muscles.set(muscle, new Set())
    muscles.get(muscle).add(exercise.name)
  }

  for (const tag of exercise.tags) {
    if (!tags.has(tag)) tags.set(tag, new Set())
    tags.get(tag).add(exercise.name)
  }
}

fs.mkdirSync('site', { recursive: true })
const exercisePageTemplate = fs.readFileSync('exercise.html', 'utf8')

const helpers = { slugify }
for (const exercise of exercises.values()) {
  const pagePath = path.join('site', `${exercise.slug}.html`)
  fs.writeFileSync(pagePath, ejs.render(exercisePageTemplate, Object.assign({}, helpers, exercise)))
}

const indexPageTemplate = fs.readFileSync('index.html', 'utf8')
const indexFile = path.join('site', 'index.html')
fs.writeFileSync(indexFile, ejs.render(indexPageTemplate, Object.assign({}, helpers, { exercises: Array.from(exercises).sort((a, b) => a.name.localeCompare(b.name)), updated: lastUpdated, muscles })))

const musclesPageTemplate = fs.readFileSync('muscles.html', 'utf8')
const musclesFile = path.join('site', 'muscles.html')
fs.writeFileSync(musclesFile, ejs.render(musclesPageTemplate, Object.assign({}, helpers, { updated: lastUpdated, muscles })))

const tagsPageTemplate = fs.readFileSync('tags.html', 'utf8')
const tagsFile = path.join('site', 'tags.html')
fs.writeFileSync(tagsFile, ejs.render(tagsPageTemplate, Object.assign({}, helpers, { updated: lastUpdated, tags })))
