#!/bin/sh
set -e
SITE=exercises.kemitchell.com
if [ ! -d node_modules ]; then
  npm ci --silent --no-progress
fi
./build | tee build.log
./tidy
rsync \
  --out-format "%n" \
  --recursive \
  --checksum \
  --copy-dirlinks \
  --copy-links \
  --delete \
  site/ "$SITE:/var/www/$SITE"
