#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

Dir.glob('data/exercises/*.yml').each do |file|
  data = YAML.load_file(file)
  data['tags']&.sort!
  File.write(file, YAML.dump(data).sub(/^---\n/, ''))
end
