#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

Dir.glob('data/**/*.yml').each do |file|
  data = YAML.load_file(file)
  data['tags']&.sort! if data.is_a?(Hash)
  File.write(file, YAML.dump(data).sub(/^---\n/, ''))
end
