#!/usr/bin/env node
import fs from 'fs'
import { globSync } from 'glob'
import yaml from 'js-yaml'

const exerciseFiles = globSync('data/exercises/*.yml')
for (const file of exerciseFiles) {
  const exercise = yaml.load(fs.readFileSync(file, 'utf8'))
  if (exercise.todo) {
    process.stdout.write(file)
    process.stdout.write('\t')
    process.stdout.write(exercise.name)
    process.stdout.write('\n')
  }
}
